[build]
  command = "bash scripts/build-wrapper.sh"
  publish = "sites/ipp-main/dist"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  GO_VERSION = "1.20"
  
# Dependency management optimization
[build.processing.js]
  bundle = true
  minify = true

# Cache node_modules for faster builds
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Per-site configuration
[context.production]
  command = "bash scripts/build-wrapper.sh"
  
[context.deploy-preview]
  command = "bash scripts/build-wrapper.sh"

# Site-specific environment variables
[context.production.environment]
  SITE_DOMAIN = "ipp.tools"
  NODE_ENV = "production"
  GO_VERSION = "1.20"

# Redirects for multi-site setup
[[redirects]]
  from = "https://neuralnarrative.ipp.tools/*"
  to = "/waitlist/neuralnarrative/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://primalposition.ipp.tools/*"
  to = "/waitlist/primalposition/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://quantumconversion.ipp.tools/*"
  to = "/waitlist/quantumconversion/index.html"
  status = 200
  force = true