[build]
  base = ""
  command = "cd sites/ipp-main && npm run build"
  publish = "sites/ipp-main/dist"

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_FLAGS = "--no-audit --no-fund"
  CI = "true"
  YARN_VERSION = "1.22.19"

# SPA redirect pattern for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache policy for immutable assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"