[build]
  publish = "sites/ipp-main/dist"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_FLAGS = "--no-audit --no-fund"
  NETLIFY_USE_YARN = "false"

# Cache configuration
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"