# IPP.TOOLS Netlify Configuration

[build]
  base = "/"
  publish = "sites/ipp-main/dist"
  command = "mkdir -p sites/ipp-main/dist && cp -r sites/ipp-main/dist-static/* sites/ipp-main/dist/ 2>/dev/null || echo '<html><head><title>IPP.TOOLS</title></head><body><h1>IPP.TOOLS</h1><p>Coming Soon</p></body></html>' > sites/ipp-main/dist/index.html"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  GO_VERSION = "1.20"

# Site-specific environment variables
[context.production.environment]
  SITE_DOMAIN = "ipp.tools"
  NODE_ENV = "production"

# Redirects for multi-site setup
[[redirects]]
  from = "https://neuralnarrative.ipp.tools/*"
  to = "/waitlist/neuralnarrative/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://primalposition.ipp.tools/*"
  to = "/waitlist/primalposition/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://quantumconversion.ipp.tools/*"
  to = "/waitlist/quantumconversion/index.html"
  status = 200
  force = true