# Primary build configuration
[build]
  command = "npm install -g yarn && yarn install && cd sites/ipp-main && yarn install && yarn build"
  publish = "sites/ipp-main/dist"

# Environment configuration
[build.environment]
  NODE_VERSION = "18.20.7"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional --frozen-lockfile"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"

# SPA routing support for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200